### ISSUE TITLE
Shorten CSS 

### ISSUE THREAD

**Issue by nikkesan** [fac19/week4-harl#30]
https://github.com/fac19/week4-harl/blob/e524c34fd1f68e9a135d8ca37276174591a9c68a/public/styles.css#L41-L45

Your margin and padding could be shortened to be: 

```css=
.container {
    margin: 1rem auto 0 auto;
    padding: 0 0.5rem;
}
```

Summarised here:
https://www.w3schools.com/css/css_margin.asp
https://www.w3schools.com/css/css_padding.asp
